services:
  - type: web
    name: critiq-backend
    runtime: node
    rootDir: critiq-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
